spring.application.name=tinyhousebackend

# MSSQL ba?lant?s? (veritaban?: proje)
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=proje
spring.datasource.username=sa
spring.datasource.password=1a2b3c

# JPA ayarlar?
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
